import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SearchProvider } from '@/contexts/search-context';
import Chatbot from '@/components/Chatbot'; // ✅ Make sure the correct path is given based on your structure

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SmartHome App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        {/* Wrapping your children and chatbot inside SearchProvider */}
        <SearchProvider>
          {children}
          <Chatbot /> {/* ✅ Your chatbot will now float globally */}
        </SearchProvider>
        
      </body>
    </html>
  );
}
