
export const accommodationsData = [
  {
    id: 1,
    title: "Luxury Ocean View Suite",
    location: "Miami, Florida",
    price: 299,
    rating: 4.9,
    reviews: 128,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036415/photo-1590381105924-c72589b9ef3f_rbuzlh.jpg",
    platform: "Booking.com",
    type: "Hotel",
    features: ["Ocean View", "King Bed", "Spa Access", "Free Breakfast"],
  },
  {
    id: 2,
    title: "Cozy Downtown Apartment",
    location: "New York, NY",
    price: 189,
    rating: 4.7,
    reviews: 95,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036578/premium_photo-1687960114927-fa6bac0a63a7_dinkuz.jpg",
    platform: "Airbnb",
    type: "Apartment",
    features: ["City View", "2 Bedrooms", "Kitchen", "Washer/Dryer"],
  },
  {
    id: 3,
    title: "Mountain Retreat Cabin",
    location: "Aspen, Colorado",
    price: 249,
    rating: 4.8,
    reviews: 76,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036595/premium_photo-1678297270408-c759a1eb6010_vafdzq.jpg",
    platform: "VRBO",
    type: "Cabin",
    features: ["Mountain View", "Fireplace", "Hot Tub", "Hiking Trails"],
  },
  {
    id: 4,
    title: "Beachfront Villa",
    location: "Cancun, Mexico",
    price: 399,
    rating: 4.9,
    reviews: 112,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036670/photo-1574362848149-11496d93a7c7_e7hlah.jpg",
    platform: "Expedia",
    type: "Villa",
    features: ["Beachfront", "Private Pool", "4 Bedrooms", "Full Staff"],
  },
  {
    id: 5,
    title: "Historic City Center Loft",
    location: "Paris, France",
    price: 219,
    rating: 4.6,
    reviews: 89,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036678/modern-multi-condos-building-blocks_k2qkja.jpg",
    platform: "Hotels.com",
    type: "Loft",
    features: ["Eiffel Tower View", "1 Bedroom", "Balcony", "Fully Renovated"],
  },
  {
    id: 6,
    title: "Seaside Cottage",
    location: "Cornwall, UK",
    price: 159,
    rating: 4.8,
    reviews: 64,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036753/residential-and-commercial-apartment-building-in-inner-sydney-suburb-of-wentworth-point-nsw_xqv4n7.jpg",
    platform: "Airbnb",
    type: "Cottage",
    features: ["Sea View", "Garden", "Fireplace", "Pet Friendly"],
  },
  {
    id: 7,
    title: "Modern Downtown Condo",
    location: "Vancouver, Canada",
    price: 179,
    rating: 4.7,
    reviews: 52,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036797/cityscape-of-a-residential-area-with-modern-apartment-buildings-new-green-urban-landscape-in_ysptxv.jpg",
    platform: "Booking.com",
    type: "Condo",
    features: ["City View", "Gym Access", "Parking", "1 Bedroom"],
  },
  {
    id: 8,
    title: "Tropical Island Bungalow",
    location: "Bali, Indonesia",
    price: 129,
    rating: 4.5,
    reviews: 78,
    image: "https://res.cloudinary.com/ddlynwvob/image/upload/v1742036747/modern-apartment-building-with-balconies-on-sunny-day_gwnimj.jpg",
    platform: "Expedia",
    type: "Bungalow",
    features: ["Beach Access", "Breakfast Included", "Outdoor Shower", "Hammock"],
  },
]

